[config]
transactions = 100
account = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
commitment = "processed"

[[endpoint]]
name = "jitostream"
url = "http://0.0.0.0:9999"
x_token = ""
kind = "jitostream"
